#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = ti.targets.arm.elf.M4F{1,0,19.6,0
#
TIRTOS_demo.xem4f: package/cfg/TIRTOS_demo.xem4f.mak

clean::
	-$(RM) package/cfg/TIRTOS_demo.xem4f.mak
