#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = ti.targets.arm.elf.M3{1,0,19.6,0
#
app.xem3: package/cfg/app.xem3.mak

clean::
	-$(RM) package/cfg/app.xem3.mak
