################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/BasicMathFunctions.c \
/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_abs_f32.c \
/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_abs_q15.c \
/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_abs_q31.c \
/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_abs_q7.c \
/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_add_f32.c \
/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_add_q15.c \
/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_add_q31.c \
/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_add_q7.c \
/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_and_u16.c \
/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_and_u32.c \
/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_and_u8.c \
/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_dot_prod_f32.c \
/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_dot_prod_q15.c \
/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_dot_prod_q31.c \
/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_dot_prod_q7.c \
/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_mult_f32.c \
/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_mult_q15.c \
/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_mult_q31.c \
/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_mult_q7.c \
/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_negate_f32.c \
/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_negate_q15.c \
/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_negate_q31.c \
/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_negate_q7.c \
/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_not_u16.c \
/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_not_u32.c \
/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_not_u8.c \
/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_offset_f32.c \
/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_offset_q15.c \
/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_offset_q31.c \
/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_offset_q7.c \
/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_or_u16.c \
/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_or_u32.c \
/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_or_u8.c \
/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_scale_f32.c \
/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_scale_q15.c \
/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_scale_q31.c \
/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_scale_q7.c \
/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_shift_q15.c \
/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_shift_q31.c \
/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_shift_q7.c \
/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_sub_f32.c \
/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_sub_q15.c \
/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_sub_q31.c \
/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_sub_q7.c \
/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_xor_u16.c \
/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_xor_u32.c \
/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_xor_u8.c 

C_DEPS += \
./BasicMathFunctions/BasicMathFunctions.d \
./BasicMathFunctions/arm_abs_f32.d \
./BasicMathFunctions/arm_abs_q15.d \
./BasicMathFunctions/arm_abs_q31.d \
./BasicMathFunctions/arm_abs_q7.d \
./BasicMathFunctions/arm_add_f32.d \
./BasicMathFunctions/arm_add_q15.d \
./BasicMathFunctions/arm_add_q31.d \
./BasicMathFunctions/arm_add_q7.d \
./BasicMathFunctions/arm_and_u16.d \
./BasicMathFunctions/arm_and_u32.d \
./BasicMathFunctions/arm_and_u8.d \
./BasicMathFunctions/arm_dot_prod_f32.d \
./BasicMathFunctions/arm_dot_prod_q15.d \
./BasicMathFunctions/arm_dot_prod_q31.d \
./BasicMathFunctions/arm_dot_prod_q7.d \
./BasicMathFunctions/arm_mult_f32.d \
./BasicMathFunctions/arm_mult_q15.d \
./BasicMathFunctions/arm_mult_q31.d \
./BasicMathFunctions/arm_mult_q7.d \
./BasicMathFunctions/arm_negate_f32.d \
./BasicMathFunctions/arm_negate_q15.d \
./BasicMathFunctions/arm_negate_q31.d \
./BasicMathFunctions/arm_negate_q7.d \
./BasicMathFunctions/arm_not_u16.d \
./BasicMathFunctions/arm_not_u32.d \
./BasicMathFunctions/arm_not_u8.d \
./BasicMathFunctions/arm_offset_f32.d \
./BasicMathFunctions/arm_offset_q15.d \
./BasicMathFunctions/arm_offset_q31.d \
./BasicMathFunctions/arm_offset_q7.d \
./BasicMathFunctions/arm_or_u16.d \
./BasicMathFunctions/arm_or_u32.d \
./BasicMathFunctions/arm_or_u8.d \
./BasicMathFunctions/arm_scale_f32.d \
./BasicMathFunctions/arm_scale_q15.d \
./BasicMathFunctions/arm_scale_q31.d \
./BasicMathFunctions/arm_scale_q7.d \
./BasicMathFunctions/arm_shift_q15.d \
./BasicMathFunctions/arm_shift_q31.d \
./BasicMathFunctions/arm_shift_q7.d \
./BasicMathFunctions/arm_sub_f32.d \
./BasicMathFunctions/arm_sub_q15.d \
./BasicMathFunctions/arm_sub_q31.d \
./BasicMathFunctions/arm_sub_q7.d \
./BasicMathFunctions/arm_xor_u16.d \
./BasicMathFunctions/arm_xor_u32.d \
./BasicMathFunctions/arm_xor_u8.d 

OBJS += \
./BasicMathFunctions/BasicMathFunctions.obj \
./BasicMathFunctions/arm_abs_f32.obj \
./BasicMathFunctions/arm_abs_q15.obj \
./BasicMathFunctions/arm_abs_q31.obj \
./BasicMathFunctions/arm_abs_q7.obj \
./BasicMathFunctions/arm_add_f32.obj \
./BasicMathFunctions/arm_add_q15.obj \
./BasicMathFunctions/arm_add_q31.obj \
./BasicMathFunctions/arm_add_q7.obj \
./BasicMathFunctions/arm_and_u16.obj \
./BasicMathFunctions/arm_and_u32.obj \
./BasicMathFunctions/arm_and_u8.obj \
./BasicMathFunctions/arm_dot_prod_f32.obj \
./BasicMathFunctions/arm_dot_prod_q15.obj \
./BasicMathFunctions/arm_dot_prod_q31.obj \
./BasicMathFunctions/arm_dot_prod_q7.obj \
./BasicMathFunctions/arm_mult_f32.obj \
./BasicMathFunctions/arm_mult_q15.obj \
./BasicMathFunctions/arm_mult_q31.obj \
./BasicMathFunctions/arm_mult_q7.obj \
./BasicMathFunctions/arm_negate_f32.obj \
./BasicMathFunctions/arm_negate_q15.obj \
./BasicMathFunctions/arm_negate_q31.obj \
./BasicMathFunctions/arm_negate_q7.obj \
./BasicMathFunctions/arm_not_u16.obj \
./BasicMathFunctions/arm_not_u32.obj \
./BasicMathFunctions/arm_not_u8.obj \
./BasicMathFunctions/arm_offset_f32.obj \
./BasicMathFunctions/arm_offset_q15.obj \
./BasicMathFunctions/arm_offset_q31.obj \
./BasicMathFunctions/arm_offset_q7.obj \
./BasicMathFunctions/arm_or_u16.obj \
./BasicMathFunctions/arm_or_u32.obj \
./BasicMathFunctions/arm_or_u8.obj \
./BasicMathFunctions/arm_scale_f32.obj \
./BasicMathFunctions/arm_scale_q15.obj \
./BasicMathFunctions/arm_scale_q31.obj \
./BasicMathFunctions/arm_scale_q7.obj \
./BasicMathFunctions/arm_shift_q15.obj \
./BasicMathFunctions/arm_shift_q31.obj \
./BasicMathFunctions/arm_shift_q7.obj \
./BasicMathFunctions/arm_sub_f32.obj \
./BasicMathFunctions/arm_sub_q15.obj \
./BasicMathFunctions/arm_sub_q31.obj \
./BasicMathFunctions/arm_sub_q7.obj \
./BasicMathFunctions/arm_xor_u16.obj \
./BasicMathFunctions/arm_xor_u32.obj \
./BasicMathFunctions/arm_xor_u8.obj 

OBJS__QUOTED += \
"BasicMathFunctions/BasicMathFunctions.obj" \
"BasicMathFunctions/arm_abs_f32.obj" \
"BasicMathFunctions/arm_abs_q15.obj" \
"BasicMathFunctions/arm_abs_q31.obj" \
"BasicMathFunctions/arm_abs_q7.obj" \
"BasicMathFunctions/arm_add_f32.obj" \
"BasicMathFunctions/arm_add_q15.obj" \
"BasicMathFunctions/arm_add_q31.obj" \
"BasicMathFunctions/arm_add_q7.obj" \
"BasicMathFunctions/arm_and_u16.obj" \
"BasicMathFunctions/arm_and_u32.obj" \
"BasicMathFunctions/arm_and_u8.obj" \
"BasicMathFunctions/arm_dot_prod_f32.obj" \
"BasicMathFunctions/arm_dot_prod_q15.obj" \
"BasicMathFunctions/arm_dot_prod_q31.obj" \
"BasicMathFunctions/arm_dot_prod_q7.obj" \
"BasicMathFunctions/arm_mult_f32.obj" \
"BasicMathFunctions/arm_mult_q15.obj" \
"BasicMathFunctions/arm_mult_q31.obj" \
"BasicMathFunctions/arm_mult_q7.obj" \
"BasicMathFunctions/arm_negate_f32.obj" \
"BasicMathFunctions/arm_negate_q15.obj" \
"BasicMathFunctions/arm_negate_q31.obj" \
"BasicMathFunctions/arm_negate_q7.obj" \
"BasicMathFunctions/arm_not_u16.obj" \
"BasicMathFunctions/arm_not_u32.obj" \
"BasicMathFunctions/arm_not_u8.obj" \
"BasicMathFunctions/arm_offset_f32.obj" \
"BasicMathFunctions/arm_offset_q15.obj" \
"BasicMathFunctions/arm_offset_q31.obj" \
"BasicMathFunctions/arm_offset_q7.obj" \
"BasicMathFunctions/arm_or_u16.obj" \
"BasicMathFunctions/arm_or_u32.obj" \
"BasicMathFunctions/arm_or_u8.obj" \
"BasicMathFunctions/arm_scale_f32.obj" \
"BasicMathFunctions/arm_scale_q15.obj" \
"BasicMathFunctions/arm_scale_q31.obj" \
"BasicMathFunctions/arm_scale_q7.obj" \
"BasicMathFunctions/arm_shift_q15.obj" \
"BasicMathFunctions/arm_shift_q31.obj" \
"BasicMathFunctions/arm_shift_q7.obj" \
"BasicMathFunctions/arm_sub_f32.obj" \
"BasicMathFunctions/arm_sub_q15.obj" \
"BasicMathFunctions/arm_sub_q31.obj" \
"BasicMathFunctions/arm_sub_q7.obj" \
"BasicMathFunctions/arm_xor_u16.obj" \
"BasicMathFunctions/arm_xor_u32.obj" \
"BasicMathFunctions/arm_xor_u8.obj" 

C_DEPS__QUOTED += \
"BasicMathFunctions/BasicMathFunctions.d" \
"BasicMathFunctions/arm_abs_f32.d" \
"BasicMathFunctions/arm_abs_q15.d" \
"BasicMathFunctions/arm_abs_q31.d" \
"BasicMathFunctions/arm_abs_q7.d" \
"BasicMathFunctions/arm_add_f32.d" \
"BasicMathFunctions/arm_add_q15.d" \
"BasicMathFunctions/arm_add_q31.d" \
"BasicMathFunctions/arm_add_q7.d" \
"BasicMathFunctions/arm_and_u16.d" \
"BasicMathFunctions/arm_and_u32.d" \
"BasicMathFunctions/arm_and_u8.d" \
"BasicMathFunctions/arm_dot_prod_f32.d" \
"BasicMathFunctions/arm_dot_prod_q15.d" \
"BasicMathFunctions/arm_dot_prod_q31.d" \
"BasicMathFunctions/arm_dot_prod_q7.d" \
"BasicMathFunctions/arm_mult_f32.d" \
"BasicMathFunctions/arm_mult_q15.d" \
"BasicMathFunctions/arm_mult_q31.d" \
"BasicMathFunctions/arm_mult_q7.d" \
"BasicMathFunctions/arm_negate_f32.d" \
"BasicMathFunctions/arm_negate_q15.d" \
"BasicMathFunctions/arm_negate_q31.d" \
"BasicMathFunctions/arm_negate_q7.d" \
"BasicMathFunctions/arm_not_u16.d" \
"BasicMathFunctions/arm_not_u32.d" \
"BasicMathFunctions/arm_not_u8.d" \
"BasicMathFunctions/arm_offset_f32.d" \
"BasicMathFunctions/arm_offset_q15.d" \
"BasicMathFunctions/arm_offset_q31.d" \
"BasicMathFunctions/arm_offset_q7.d" \
"BasicMathFunctions/arm_or_u16.d" \
"BasicMathFunctions/arm_or_u32.d" \
"BasicMathFunctions/arm_or_u8.d" \
"BasicMathFunctions/arm_scale_f32.d" \
"BasicMathFunctions/arm_scale_q15.d" \
"BasicMathFunctions/arm_scale_q31.d" \
"BasicMathFunctions/arm_scale_q7.d" \
"BasicMathFunctions/arm_shift_q15.d" \
"BasicMathFunctions/arm_shift_q31.d" \
"BasicMathFunctions/arm_shift_q7.d" \
"BasicMathFunctions/arm_sub_f32.d" \
"BasicMathFunctions/arm_sub_q15.d" \
"BasicMathFunctions/arm_sub_q31.d" \
"BasicMathFunctions/arm_sub_q7.d" \
"BasicMathFunctions/arm_xor_u16.d" \
"BasicMathFunctions/arm_xor_u32.d" \
"BasicMathFunctions/arm_xor_u8.d" 

C_SRCS__QUOTED += \
"/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/BasicMathFunctions.c" \
"/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_abs_f32.c" \
"/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_abs_q15.c" \
"/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_abs_q31.c" \
"/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_abs_q7.c" \
"/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_add_f32.c" \
"/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_add_q15.c" \
"/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_add_q31.c" \
"/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_add_q7.c" \
"/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_and_u16.c" \
"/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_and_u32.c" \
"/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_and_u8.c" \
"/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_dot_prod_f32.c" \
"/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_dot_prod_q15.c" \
"/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_dot_prod_q31.c" \
"/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_dot_prod_q7.c" \
"/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_mult_f32.c" \
"/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_mult_q15.c" \
"/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_mult_q31.c" \
"/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_mult_q7.c" \
"/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_negate_f32.c" \
"/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_negate_q15.c" \
"/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_negate_q31.c" \
"/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_negate_q7.c" \
"/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_not_u16.c" \
"/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_not_u32.c" \
"/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_not_u8.c" \
"/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_offset_f32.c" \
"/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_offset_q15.c" \
"/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_offset_q31.c" \
"/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_offset_q7.c" \
"/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_or_u16.c" \
"/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_or_u32.c" \
"/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_or_u8.c" \
"/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_scale_f32.c" \
"/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_scale_q15.c" \
"/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_scale_q31.c" \
"/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_scale_q7.c" \
"/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_shift_q15.c" \
"/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_shift_q31.c" \
"/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_shift_q7.c" \
"/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_sub_f32.c" \
"/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_sub_q15.c" \
"/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_sub_q31.c" \
"/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_sub_q7.c" \
"/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_xor_u16.c" \
"/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_xor_u32.c" \
"/Users/venkim/ti/CMSIS_5-5.7.0/CMSIS/DSP/Source/BasicMathFunctions/arm_xor_u8.c" 


